services:
  gitlab-discord:
    build: .
    ports:
      - "8000:8000"
    environment:
      DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1470227849641459742/9DBDzwPy7p5rIWtOR-8WJs96zWqHj0WXm7O11BhBWdA3hDPsUJUSH3eKq_B2NynlQ9nC"
      GITLAB_WEBHOOK_TOKEN: "chamchi123"
    restart: unless-stopped
